ARG BASE_IMAGE=spack/ubuntu-jammy
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /build/

RUN spack install -j4 petsc+kokkos && \
    spack install python && \
    spack install py-setuptools && \
    spack install py-cython && \
    spack install py-numpy && \
    spack install py-petsc4py

LABEL maintainer='Steven Dargaville'
LABEL description='petsc_spack'