ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

RUN echo Etc/UTC > /etc/timezone && ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  autoconf \
  automake \
  bash-completion \
  ca-certificates \
  chrpath \
  cmake \
  curl \
  g++ \
  gcc \
  gfortran \
  git \
  less \
  libblis-serial-dev \
  liblapack-dev \
  libtool \
  locales \
  m4 \
  make \
  openssl \
  pkg-config \
  ripgrep \
  zlib1g-dev \
  python3-virtualenv \
  python3.10-venv \
  python3.10-dev \
  wget \
  gnupg \
  valgrind \
  vim \  
  && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8

WORKDIR /tmp

SHELL ["/bin/bash", "-c"]

# Install the intel compilers and mpi
RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
RUN apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB && rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
RUN echo "deb https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
RUN apt update && apt install -y --no-install-recommends intel-basekit intel-hpckit && cd /opt/intel/oneapi && rm -rf vtune ipp dnnl dpcpp-ct debugger dal advisor ccl mkl umf tbb pti ippcp dpl
ENV LD_LIBRARY_FLAGS="-L/opt/intel/oneapi/compiler/latest/lib/"

WORKDIR /build
ARG PETSC_GIT_BRANCH=release

# Have to build a venv for python as pip/numpy now complain
ENV VIRTUAL_ENV=/my-venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install python packages (should be in the venv not globally)
RUN wget https://bootstrap.pypa.io/get-pip.py \
 && python3 ./get-pip.py && pip install numpy && pip install Cython && pip install setuptools

# Install petsc
ENV PETSC_DIR=/build/petsc
ENV PETSC_ARCH=arch-linux-intel
RUN source /opt/intel/oneapi/setvars.sh && \
  git clone --depth=1 --branch=$PETSC_GIT_BRANCH https://gitlab.com/petsc/petsc.git && \
  cd petsc && \
  OPT='-O2'; \
  python3 configure \
    --with-cc=mpiicx --with-cxx=mpiicpx --with-fc=mpiifx \
    LDFLAGS=-Wl,-rpath,/opt/intel/oneapi/compiler/latest/lib/ \
    --with-debugging=0 COPTFLAGS="$OPT" CXXOPTFLAGS="$OPT" FOPTFLAGS="$OPT" \
    --download-metis \
    --download-parmetis \
    && \
  make

LABEL maintainer='Steven Dargaville'
LABEL description='petsc_intel'
