ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

RUN echo Etc/UTC > /etc/timezone && ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  autoconf \
  automake \
  bash-completion \
  ca-certificates \
  chrpath \
  cmake \
  curl \
  g++ \
  gcc \
  gfortran \
  git \
  less \
  libblis-serial-dev \
  liblapack-dev \
  libtool \
  locales \
  m4 \
  make \
  openssl \
  pkg-config \
  ripgrep \
  zlib1g-dev \
  python3-virtualenv \
  python3.10-venv \
  python3.10-dev \
  wget \
  gnupg \
  valgrind \
  vim \
  && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8

WORKDIR /tmp

# Install the nvidia compilers
RUN curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg && echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | tee /etc/apt/sources.list.d/nvhpc.list 
# Install the package but also delete most of the tools we don't need, we only need the compilers
RUN apt-get update -y && apt-get install -y nvhpc-25-1 && rm -rf /opt/nvidia/hpc_sdk/Linux_x86_64/25.1/profilers && rm -rf /opt/nvidia/hpc_sdk/Linux_x86_64/25.1/math_libs && rm -rf /opt/nvidia/hpc_sdk/Linux_x86_64/25.1/comm_libs && rm -rf /opt/nvidia/hpc_sdk/Linux_x86_64/25.1/cuda
ENV PATH="/opt/nvidia/hpc_sdk/Linux_x86_64/25.1/compilers/bin:$PATH"

WORKDIR /build
ARG PETSC_GIT_BRANCH=release

# Have to build a venv for python as pip/numpy now complain
ENV VIRTUAL_ENV=/my-venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install python packages (should be in the venv not globally)
RUN wget https://bootstrap.pypa.io/get-pip.py \
 && python3 ./get-pip.py && pip install numpy && pip install Cython && pip install setuptools

# Install petsc
ENV PETSC_DIR=/build/petsc
ENV PETSC_ARCH=arch-linux-nvidia
RUN git clone --depth=1 --branch=$PETSC_GIT_BRANCH https://gitlab.com/petsc/petsc.git && \
  cd petsc && \
  OPT='-O2'; \
  python3 configure \
    --with-cc=nvc --with-cxx=nvc++ --with-fc=nvfortran \
    --with-debugging=0 COPTFLAGS="$OPT" CXXOPTFLAGS="$OPT" FOPTFLAGS="$OPT" \
    --download-metis \
    --download-parmetis \
    --download-mpich \
    && \
  make
ENV PATH="/build/petsc/arch-linux-nvidia/bin:$PATH"

LABEL maintainer='Steven Dargaville'
LABEL description='petsc_nvidia'
