ARG BASE_IMAGE=spack/ubuntu-noble
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /build/

# Build petsc with static libraries
# and also petsc with dynamic libraries and kokkos
# Pin the petsc4py install to the dynamic + kokkos build
RUN spack install -j4 petsc@main~shared && \
    spack install -j4 petsc@main+kokkos && \
    spack install python py-setuptools py-cython py-numpy py-petsc4py ^petsc@main+kokkos

LABEL maintainer='Steven Dargaville'
LABEL description='petsc_spack'
