name: Docker Image CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3         

  build_petsc:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - name: Build Docker image for pull requests
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          file: ./dockerfiles/Dockerfile_petsc
          tags: stevendargaville/petsc:latest